apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: @deployment.name@
  name: @deployment.name@
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: @deployment.name@
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: @deployment.name@
    spec:
      containers:
        - image: zayanimal/website:v1
          name: @deployment.name@
          resources:
            requests:
              cpu: '200m'
              memory: '256Mi'
            limits:
              cpu: '300m'
              memory: '512Mi'
          envFrom:
            - configMapRef:
                name: @deployment.name@-cm
            - secretRef:
                name: secret
          ports:
            - containerPort: 8080
              protocol: TCP