apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: default
spec:
  type: NodePort
  selector:
    app: db-postgres
  ports:
    - nodePort: 30123
      protocol: TCP
      port: 5432
      targetPort: 5432