apiVersion: v1
kind: Service
metadata:
  labels:
    app: @deployment.name@
  name: @deployment.name@
  namespace: @deployment.name@
spec:
  type: NodePort
  selector:
    app: @deployment.name@
  ports:
    - nodePort: 30123
      port: 8080
      protocol: TCP
      targetPort: 8080