apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - nodePort: 30223
      port: 8080
      protocol: TCP
      targetPort: 8080