apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: @deployment.name@
  name: @deployment.name@
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: @deployment.name@
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: @deployment.name@
    spec:
      containers:
        - image: luksa/kubia:v1
          imagePullPolicy: IfNotPresent
          name: @deployment.name@
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30