apiVersion: v1
kind: Service
metadata:
  name: website-back-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: website-back-http
      protocol: TCP
      port: 80
      targetPort: website-back-port
