apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  POSTGRES_USER: $(echo -n "postgres" | base64 -w0)
  POSTGRES_PASSWORD: $(echo -n "secret" | base64 -w0)
  JWT_SECRET: $(echo -n "zayanimal" | base64 -w0)